#!/bin/bash

if [ $# -eq 1 ]
then
   echo "./dev/dev$1/bin/node stop"
   ./dev/dev$1/bin/node stop
elif [ $# -eq 2 ]
then
   for i in $(seq $1 $2)
   do
      echo "./dev/dev$i/bin/node stop"
      ./dev/dev$i/bin/node stop
   done
else
   echo "USAGE: $0 dev_NUM"
   echo "       $0 starting_NUM ending_NUM"
   exit -1
fi
